FROM mcr.microsoft.com/dotnet/sdk:10.0

WORKDIR /src

COPY ["NuGet.Config", "."]
COPY ["dotnet-tools.json", "."]
COPY ["src/BookIt.Domain/BookIt.Domain.csproj", "src/BookIt.Domain/"]
COPY ["src/BookIt.Application/BookIt.Application.csproj", "src/BookIt.Application/"]
COPY ["src/BookIt.Infrastructure/BookIt.Infrastructure.csproj", "src/BookIt.Infrastructure/"]
COPY ["src/BookIt.Api/BookIt.Api.csproj", "src/BookIt.Api/"]
RUN dotnet restore "src/BookIt.Api/BookIt.Api.csproj" --configfile NuGet.Config
RUN dotnet tool restore

EXPOSE 8080
